Repository NEMRI-org/primo-optimizer, pull requests merged in 2024-08, with the labels that each got.

#1 Housekeeping
  .addheader.yml
  .github/CODEOWNERS
  .github/workflows/checks.yml
  README.md
  docs/conf.py
  file_header.txt
  primo/__init__.py
  primo/data_parser/__init__.py
  primo/data_parser/data_model.py
  primo/data_parser/input_parser.py
  primo/demo/tests/__init__.py
  primo/opt_model/__init__.py
  primo/opt_model/base_model.py
  primo/opt_model/opt_model.py
  primo/opt_model/tests/__init__.py
  primo/opt_model/tests/test_base_model.py
  primo/opt_model/tests/test_opt_model.py
  primo/utils/__init__.py
  primo/utils/census_utils.py
  primo/utils/clustering_utils.py
  primo/utils/config_utils.py
  primo/utils/demo_utils.py
  primo/utils/download_utils.py
  primo/utils/elevation_utils.py
  primo/utils/estimation_utils.py
  primo/utils/geo_utils.py
  primo/utils/kpi_utils.py
  primo/utils/map_utils.py
  primo/utils/multiple_scenario_util.py
  primo/utils/opt_utils.py
  primo/utils/proximity_utils.py
  primo/utils/raise_exception.py
  primo/utils/setup_arg_parser.py
  primo/utils/setup_logger.py
  primo/utils/solvers.py
  primo/utils/tests/__init__.py
  primo/utils/tests/test_census_utils.py
  primo/utils/tests/test_clustering_utils.py
  primo/utils/tests/test_config_utils.py
  primo/utils/tests/test_demo_utils.py
  primo/utils/tests/test_elevation_utils.py
  primo/utils/tests/test_estimation_utils.py
  primo/utils/tests/test_geo_utils.py
  primo/utils/tests/test_headers.py
  primo/utils/tests/test_imports.py
  primo/utils/tests/test_kpi_utils.py
  primo/utils/tests/test_map_utils.py
  primo/utils/tests/test_proximity_utils.py
  setup.py
  stagedfright.py
Labels: documentation

#5 Repository badges
  .github/workflows/checks.yml
  README.md
Labels: documentation

#7 TEST: Update workflow to skip tests that require secrets when PR is opened. Fixes #2
  .github/workflows/checks.yml
  primo/utils/tests/test_census_utils.py
  primo/utils/tests/test_demo_utils.py
  primo/utils/tests/test_elevation_utils.py
  pytest.ini
Labels: testing

#8 Integration testing
  .github/workflows/checks.yml
  .github/workflows/demo.yml
  README.md
  codecov.yml
  conda-env.yml
  primo/demo/tests/test_demo.py
  primo/utils/tests/test_headers.py
  pytest.ini
  setup.py
Labels: testing

#17 Added `fill_missing_value` attribute in Metric class
  .stagedfright/checks.py
  primo/data_parser/default_data.py
  primo/data_parser/metric_data.py
  primo/data_parser/tests/test_metric_data.py
  primo/data_parser/tests/test_well_data_column_names.py
  primo/data_parser/well_data_column_names.py
Labels: enhancement
